name: C.J. Hayden
favicon: null
layout_spectrum: 0.8092496735043824
typography_spectrum: 0.3042492074891925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fac835'
    - '#383838'
    - '#7a7a7a'
    - '#c6c6c6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
