name: C.J. Hayden
favicon: null
layout_spectrum: 0.49888
typography_spectrum: 0.86726
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e8140'
    - '#ffcc33'
    - '#6f3027'
    - '#000000'
    - '#ffffff'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
