name: C.J. Hayden
favicon: null
layout_spectrum: 0.5645
typography_spectrum: 0.86726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcdd73'
    - '#996533'
    - '#d9a365'
    - '#281703'
    - '#306500'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
