name: C.J. Hayden
favicon: null
layout_spectrum: 0.49888
typography_spectrum: 0.57495
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffcc33'
    - '#008127'
    - '#000000'
    - '#e86924'
    - '#8c733c'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
